### PR TITLE
Vastly improved monopoly bot checking, and added a few missing bots

### PR DESCRIPTION
**Pull request by HcgRandon**
Hi, I'm the creator of Ayana, I wanted to help you out a little bit. I have improved your monopoly checking code quite a bit and added a few missing bots.

Enjoy 👍

(Brought over from: https://github.com/Lovinity/loveybot/pull/2)

### CODE REVIEW

**Comment by itslukej** [comment]
@everyone wb

**Comment by TheAkio** [comment]
Nice, all those bots are way too large... Good idea!

**Comment by RobinJoh95** [comment]
This is a good idea, now it's not all for nothing 👍

**Comment by ducc** [comment]
**HAVING TO REWRITE MY COMMENTS HAS MADE ME EXCESSIVELY MAD, HERE IS WHAT I AM GOING TO DO TO THIS REPOSITORY IF THIS PULL REQUEST IS MERGED AND DABBOT IS ADDED TO THE MONOPOLY CHECKING:**


**GOOD LUCK, KIDDO**

- The professional dabBot development team.

**Comment by Lovinity** [comment]
ducc please do not make comments that are not constructive to the development of this repository. Thank you.

**Comment by Lovinity** [comment]
Thank you for the improvements ^^

**Comment by macdja38** [comment]
Is Aethex still a thing?

**Comment by Lovinity** [comment]
Yes Aethex is still in operation to my knowledge

**Pull request merged**
